updates mlctl init (#18)
intuit/mlctl pull request #19
Opened 2021-07-26 02:54 UTC by deepk2u

## Goals of this PR :tada:
https://github.com/intuit/mlctl/issues/18

2021-07-26 04:42 UTC, awcchungster commented on mlctl/clis/template/{{cookiecutter.package_name}}/model/train.py
> +    """
I think there should be a `train()` call within main

2021-07-26 04:43 UTC, awcchungster commented on mlctl/clis/template/{{cookiecutter.package_name}}/model/train.py
> +    """
correction, based on the setup.py, the `train()` is called. In that case, the training adapter should be embedded there

2021-07-26 04:46 UTC, awcchungster commented on tests/clis/mlctl_init/setup.py
> +            'example_predict = model.predict:predict',
For hosting, I think we are missing the load model on container start. Refer to the examples here:

https://github.com/intuit/baklava/tree/master/examples/7-predict-initializer

2021-07-26 04:47 UTC, awcchungster requested changes
Minor changes to the init structure and functions

2021-08-14 04:04 UTC, srivathsanvc commented
@deepk2u - can you please update based on the review comments?

2021-08-14 04:07 UTC, srivathsanvc commented on mlctl/clis/template/cookiecutter.json
> +  "package_name": "Boilerplate ML Model",
```suggestion
  "package_name": "Sample ML Model",
```

2021-08-14 04:07 UTC, srivathsanvc commented on mlctl/clis/template/cookiecutter.json
> +  "description": "Python Boilerplate ML model contains all the boilerplate you need to create a working ML model project."
```suggestion
  "description": "Sample ML model contains all the boilerplate code required to create a working ML model project."
```

2021-08-14 04:07 UTC, srivathsanvc commented on mlctl/clis/template/{{cookiecutter.package_name}}/model/train.py
> +def train():
```suggestion
def train(ta):
```

2021-08-14 17:51 UTC, closed without merging